### ISSUE TITLE
INSTALLING w4SP-LAB ** Fatal ERROR during Scapy downolading **

### ISSUE THREAD

**Issue by avalenteAvo** [e4bongcloud/w4sp-lab#1]
Dear e4bongcloud,
I need to thank you for your steps. They were working perfectly until this problem I had during lab installation.
It is appearing installation generated an exception from Scapy due to no longer Python 2.
I am not able to understand what I need to do and if I need to modify something.
I would extremely appreciate your kind feedback.
Thank you

![errorScapy](https://github.com/e4bongcloud/w4sp-lab/assets/104693583/ef8bba99-9efe-4df2-bafe-cdd22509babd)

**Comment by e4bongcloud** [comment]
I need to switch to Python 3. In Kali -default, you probably have Python 3.11 or Python 3.10 installed. You can run that version.

However, the unfortunate fact is that I also attempted to fix bugs in the w4sp-lab project and distribute it, but I failed to fix the bugs myself. Therefore, even if it runs, it is likely that it will not work as described in the book where w4sp-lab was originally released.

**Comment by avalenteAvo** [comment]
I solved the issue adding in the Victims Dockerfile (as root) the github branch of older Scapy releases v.2.4.4
**RUN git clone --branch v.2.4.4 https://github.com/secdev/scapy.git**

**Comment by avalenteAvo** [comment]
From scapy persective the problem is solved including the following line code
RUN git clone --branch v.2.4.4 https://github.com/secdev/scapy.git
in the victims DOCKERFILE (to modify the file please enter as root user).
